# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-01 19:47
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coInvesterDetails',
            fields=[
                ('coInvesterId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('dob', models.CharField(max_length=256, null=True)),
                ('idProof', models.CharField(max_length=255, null=True)),
                ('idProofNo', models.CharField(max_length=255, null=True)),
                ('pan', models.CharField(max_length=255, null=True)),
                ('relation', models.CharField(max_length=255, null=True)),
                ('address1', models.CharField(max_length=255, null=True)),
                ('address2', models.CharField(max_length=255, null=True)),
                ('address3', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('pin', models.CharField(max_length=6, null=True)),
                ('correspondenceAddress1', models.CharField(max_length=255, null=True)),
                ('correspondenceAddress2', models.CharField(max_length=255, null=True)),
                ('correspondenceAddress3', models.CharField(max_length=255, null=True)),
                ('correspondenceCity', models.CharField(max_length=255, null=True)),
                ('correspondenceState', models.CharField(max_length=255, null=True)),
                ('correspondencePin', models.CharField(max_length=6, null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('marital', models.CharField(max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='investerBankDetail',
            fields=[
                ('investerBankId', models.AutoField(primary_key=True, serialize=False)),
                ('accountNo', models.CharField(max_length=255, null=True)),
                ('accountName', models.CharField(max_length=255, null=True)),
                ('ifscCode', models.CharField(max_length=255, null=True)),
                ('bankName', models.CharField(max_length=255, null=True)),
                ('branchDetail', models.CharField(max_length=255, null=True)),
                ('accountType', models.CharField(choices=[('0', 'CURRENT'), ('1', 'SAVING'), ('2', 'SINGLE BIZ'), ('3', 'JOINT ACCOUNT')], max_length=20)),
                ('cancelCheque', models.CharField(max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='investerDetails',
            fields=[
                ('investerId', models.AutoField(primary_key=True, serialize=False)),
                ('investerName', models.CharField(default='', max_length=256, null=True)),
                ('fatherName', models.CharField(default='', max_length=256, null=True)),
                ('dateOfBirth', models.DateTimeField(auto_now=True)),
                ('occupation', models.CharField(default='', max_length=256, null=True)),
                ('occupationSpecify', models.CharField(default='', max_length=256, null=True)),
                ('idProof', models.CharField(default='', max_length=256, null=True)),
                ('idProofNo', models.CharField(default='', max_length=256, null=True)),
                ('pan', models.CharField(default='', max_length=256, null=True)),
                ('address1', models.CharField(default='', max_length=255, null=True)),
                ('address2', models.CharField(default='', max_length=255, null=True)),
                ('address3', models.CharField(default='', max_length=255, null=True)),
                ('city', models.CharField(default='', max_length=255, null=True)),
                ('state', models.CharField(default='', max_length=255, null=True)),
                ('pin', models.CharField(default='000000', max_length=6, null=True)),
                ('correspondenceAddress1', models.CharField(default='', max_length=255, null=True)),
                ('correspondenceAddress2', models.CharField(default='', max_length=255, null=True)),
                ('correspondenceAddress3', models.CharField(default='', max_length=255, null=True)),
                ('correspondenceCity', models.CharField(default='', max_length=255, null=True)),
                ('correspondenceState', models.CharField(default='', max_length=255, null=True)),
                ('correspondencePin', models.CharField(default='', max_length=255, null=True)),
                ('contactno', models.CharField(default='', max_length=10, null=True)),
                ('email', models.EmailField(default='', max_length=255, null=True)),
                ('marital', models.CharField(default='', max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='investerPaymentDetail',
            fields=[
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('investAmount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paymode', models.CharField(max_length=100)),
                ('checkno', models.CharField(default='', max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('invester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invester.investerDetails')),
            ],
        ),
        migrations.CreateModel(
            name='investerPlanDetail',
            fields=[
                ('investerPlanId', models.AutoField(primary_key=True, serialize=False)),
                ('branchCode', models.CharField(max_length=256, null=True)),
                ('investPeriod', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('installmentMode', models.CharField(max_length=256)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advisor.advisorDetail')),
                ('advisorPlan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.advisorPlanDetail')),
                ('invester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invester.investerDetails')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.investerPlanDetail')),
            ],
        ),
        migrations.AddField(
            model_name='investerpaymentdetail',
            name='investerPlan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invester.investerPlanDetail'),
        ),
        migrations.AddField(
            model_name='investerbankdetail',
            name='invester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invester.investerDetails'),
        ),
        migrations.AddField(
            model_name='coinvesterdetails',
            name='invester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invester.investerDetails'),
        ),
    ]
