# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-07 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('invester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investerdetails',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branchDetail'),
        ),
    ]
