# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invester', '0002_investerdetails_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investerbankdetail',
            old_name='accountName',
            new_name='accountNumber',
        ),
        migrations.RenameField(
            model_name='investerbankdetail',
            old_name='accountNo',
            new_name='bankCity',
        ),
        migrations.RenameField(
            model_name='investerbankdetail',
            old_name='branchDetail',
            new_name='bankPin',
        ),
        migrations.RenameField(
            model_name='investerbankdetail',
            old_name='cancelCheque',
            new_name='branchAddress',
        ),
        migrations.RenameField(
            model_name='investerbankdetail',
            old_name='ifscCode',
            new_name='branchState',
        ),
        migrations.RemoveField(
            model_name='coinvesterdetails',
            name='dob',
        ),
        migrations.AddField(
            model_name='investerbankdetail',
            name='ifsc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investerbankdetail',
            name='payeeName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
