# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invester', '0003_auto_20170108_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinvesterdetails',
            name='dob',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
