# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-07 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branchDetail',
            fields=[
                ('branchID', models.AutoField(primary_key=True, serialize=False)),
                ('branchCode', models.CharField(max_length=255)),
                ('branchName', models.CharField(default='Aviral', max_length=255, null=True)),
            ],
        ),
    ]
